# source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project`
platform :ios, '8.2'

target 'auaBnB' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for auaBnB
	pod 'Backendless'
	pod 'KFSwiftImageLoader', '~> 2.0'

end
