# Uncomment this line to define a global platform for your project
platform :ios, '8.2'

target 'SuretGramm' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for salem
	pod 'Backendless'
	pod 'KFSwiftImageLoader', '~> 2.0'
	pod 'SwiftyJSON'
	

end
